### ISSUE TITLE
change in the bricks tree behavior

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#169]
**Describe the bug**
@servoz said:
> in pipeline manager [the little triangles hiding or showing the bricks inside](https://github.com/populse/populse_mia/files/4852027/temp1.pdf) seem to have a different behavior than before (if i am not wrong, before it let see all the bricks by default, now it looks like it's the opposite. Do you have any idea why? (minor remark)

**Comment by denisri** [comment]
I did this on purpose but didn't take time to discuss about it.
Before this, the entire bricks tree was open, entirely unfolded. In nipype there are hundreds (thousands ?) of bricks, and it was extremely difficult to find a specific one quickly unless it was one of the very first ones. Of course mia_processes bricks were first thus *yours* were easily accessed. But for others it required more than 10 clicks to fold some parts of the trees until we actually see the brick we are looking for, even if we know where it is in the tree. I used it many many times during development and testing, and it was particularly boring (so I don't exaggerate when I say "10 clicks", it was 11 for me when testing a nipype spm.Smooth for instance, at each test trial and of course I had to do it several hundred times). So it became obvious for me that this was not ergonomically OK for users. The purpose of having a tree is precisely to organize things and hide the plethora of elements when you don't need them all at the same time, otherwise a tree is not needed and we could make a flat list instead. Plus it gave much visibility to the first bricks and was really hiding bricks later in the list (lost in the mass), which was unfair ;)
But actually we didn't discuss it and it is still possible to come back to the former behavior, or make a config option to drive this.

**Comment by servoz** [comment]
Okay, I understand the problem very well.
What we need is to have a tree in which we can unfold what we want and fold what we want and that this state remains saved when we leave mia for the next restart.
I confess I've never explored this (but it would be really nice to know how to do it!). In fact, the reason I never tried to find a way to keep the visual of the tree is that it is possible to determine what we see in this tree from File > Package library manager. Instead of a long speech, [here's an example.](https://mycore.core-cloud.net/index.php/s/xiYZ8II4ZprHNY9)
But indeed, if we could keep the desired unfolding of the tree for a next restart plus the possibility to see only the parts of the tree that we want to see (File > Package library manager) it would be very wonderful !

**Comment by servoz** [comment]
and in fact by selecting what we want to see (File > Package Library Manager) it may seem more interesting to have the "all unfolded" status, otherwise it will take at least one more click to access the desired brick :-) BUT I'm not going to fight for one click, so it's ok to keep the change you made. What would be really great, as said above, would be to be able to keep the state of the tree when we restart mia

**Comment by denisri** [comment]
> What would be really great, as said above, would be to be able to keep the state of the tree when we restart mia

This can probably be done when saving the project.

**Comment by servoz** [comment]
It's one option, but i am not sure this is every time the good option, because I think it will be necessary to deal one day with [several databases in the same instance of mia](https://github.com/populse/populse_mia/issues/150) (it's a big thought that should be taken into account as soon as possible ... finally when we'll have a little time for it).
Moreover when we start a mia instance, there is no project still open (well, yes but it's a temporary project in /tmp).
And finally, with this option, the display of the tree would be linked to a project. It can make sense, but don't we want it to be linkefor to mia itself ? (config of mia, like in File  > Package Library Manager).
it's just a display but it's not trivial ...
