### ISSUE TITLE
No module named 'anatomist'

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#200]
Previously I had installed Populse_mia in a virtual environment, it worked well.

Since I updated to the latest version of Populse_mia,  an error message indicates that 'anatomist' module is not found when I run it.
I installed anatomist-free and anatomist-gpl in the same virtual environment, but the problem is the same.

BrainVisa may need to be installed ? Install with Singularity ?

Thank you.

Olivier

**Comment by servoz** [comment]
Mia V2 is now using the casa distro environment of brainvisa while waiting to make our own based on the brainvisa one (the final goal being to merge brainvisa and populse).
You can find a minimal recipe to install the singularity container under linux [here](https://github.com/populse/populse_mia/blob/master/developer_doc/UsingVirtualisation.md).
I have been working with it for several months and it works very well.

**Comment by servoz** [comment]
I'm closing this ticket but feel free to reopen it if you experience any problems.

**Comment by denisri** [comment]
Couldn't we make the dependency on anatomist optional (as it was before) ? I mean, if anatomist is not present and cannot be imported, then viewers based on it are disabled - maybe all of them are disabled and no viewer can be used, but populse_mia still runs ? I had done it this way for the "anatomist viewer".

**Comment by servoz** [comment]
@Celinnnne  is currently working on the data_viewer and indeed, in the last merge with master, we didn't keep the dependency on anatomist optional (but it wasn't really thought out, basically it is the result of a merger error!).

However I think:
- that we should encourage users to use virtualisation to simplify installation problems
- that if they don't use virtualisation and unless they manage to install anatomist dependency by themselves (I doubt they are simple users in this case), they won't have access to the data_viewer offered with it. It's a pity...

We can of course make again optional anatomist dependency and we will do so ASAP, in order to use mia without data_viewer (@Celinnnne  do you have time to look at this or do you want me to do it?).

**Comment by denisri** [comment]
Sure I would like to encourage users to use virtualization and anatomist, but I'm just not sure we should _force_ them. Having a good viewer should be a better motivation than being forced ;)
But I'm otherwise not complaining: if users use anatomist, it's good for me :)
I have a couple of other remarks, maybe they should go in another ticket / discussion...

**Comment by servoz** [comment]
Ok, the scope of the data viewer (instantiation, how it works, etc.) goes far beyond this ticket. 
We're already going to put back as before master to fix this ticket and discuss the data viewer in the one you opened #201.
I'm closing this ticket (@montigno feel free to reopen it if you still have problems with it).

**Comment by montigno** [comment]
I installed  the singularity container,  It looks good (the installation was long !).
Anatomist launches fine but does not display NIFTI images (whether 3D, Axial, Sagittal or Coronal). I will take the time to look at the settings.

I modified the 'data_viewer_tab.py' file in 'populse_mia/python/populse_mia/user_interface/data_viewer', I commented out the lines containing the viewer_name variable, and it works (while waiting for the merge brainvisa and populse)

**Comment by servoz** [comment]
Perfect.
So this ticket is fixed ?

**Comment by montigno** [comment]
We can closed, I will see the Anatomist display problem later

**Comment by servoz** [comment]
We are currently working on the Data Viewer instantiation (it is currently the result of a merger accident of the development branch with master).
For the moment the Data Viewer would not have been available on master so I suggest you wait a bit as it is still a work in progress (you might waste time working on something that will soon change).

**Comment by servoz** [comment]
We have made some changes in master branch to fix this issue.
You can now use mia directly without brainvisa container (as before), but in this case you will not have access to the data_viewer or with the container. 
n the latter case, please open a ticket if you experience issues with the data viewer (still under development).

**Comment by montigno** [comment]
I reinstalled it and it's ok for me.
