### ISSUE TITLE
Mia exit with "Segmentation fault (core dumped)" if Data Viewer tab is activated

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#205]
- Observed only if Anatomist is active (click on the Data Viewer tab).
- when we exit mia, the following message appears in the stdout:
`Segmentation fault (core dumped)`
- It's not a big deal. There is no mia crash. So it's not a priority at all, just to have a nice stdout ...

**Comment by denisri** [comment]
Yes that's a known issue in pyanatomist. It does not exit cleanly, and this has been so for many years. It's very difficult to fix, and I'll explain in a few words:
pyanatomist is a python binding and extension library on top of anatomist (C++). Pyanatomist registers some python extensions in Anatomist global (or application-wide) objects lists. When exiting, libraries exit functions are called in an order we don't really master. Global destructors are called in an order we don't decide. One possible scenario is that, at some point the python engine gets stopped, while the C++ registries still contain pointers to python extension objects (or to their C++ wrapper more precisely), so when C++ objects get destroyed, they manipulate deleted objects. Or inversely. Both may occur actually. In this situation reference counting is a real problem, since it simply forbids to delete objects in a controlled order. Moreover I admit that some objects are not correctly destroyed in Anatomist. Well it would require some work too, probably several days/weeks to try to cleanup everything. That's probably worth the effort but nobody has time for that...

**Comment by servoz** [comment]
ok I understand very well and so I think it is urgent to wait to fix this issue ...
The best thing we can do for now is to close this ticket.
Anyway, it doesn't affect the operation of the mia, a normal user won't pay attention to it and we can live with a standard output where the last line is `Segmentation fault (core dumped)`!
