### ISSUE TITLE
MIA: writing output files in "derived_data" folder

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#25]
Some posts exist on this populse_sandbox issue (populse/populse_sandbox#5).
To sum up:
- It is not easy for all the platforms ... :smile: 

<br/><br/><br/><br/><br/><br/>

---
This is a copy of populse/populse_sandbox#5. Do not forget to close concomitantly the populse/populse_sandbox#5 and this issue !_

**Comment by dhrbn** [comment]
Nipype already copies output files from its working directory to the right directory, maybe we could examine this in greater depth

**Comment by M40V** [comment]
It is possible to use a Datasink node from nipype to select the output folder. When using this node, the output will be produced in the specified directory instead of the one where we find the input.

It could be interesting to add an argument to choose the output directory in capsul or soma-workflow or else we'll have to overload them to solve this issue.

```
import nipype.interfaces.io as nio
from nipype.pipeline.engine import Workflow, Node, MapNode
import nipype.interfaces.spm as spm
from nipype.interfaces.matlab import MatlabCommand

MatlabCommand.set_default_paths('/home/jibril/spm12')

smooth = Node(spm.Smooth(in_files=["/home/jibril/Bureau/Projects/populse_mia/projects/test_bug42/data/raw_data/Guerbet-C6-2014-Rat-K39-Tube9-2014-02-11_08-01-22-3-G2_Guerbet_ADC--.nii "]), name='smoothnode')

datasink = Node(nio.DataSink(), name="datasink")
datasink.inputs.base_directory = './'
datasink.inputs.container = '/home/jibril/Bureau/Projects/populse_mia/projects/test_bug42/data'

workflow = Workflow(name='workflow')
workflow.connect([(smooth, datasink, [("smoothed_files", "derived_data")])])
workflow.run()
```

**Comment by denisri** [comment]
Well, in this case I guess you're not using Capsul and Soma-Workflow any longer, but Nipype workflows. Capsul is compatible with nipype interfaces, but is not dealing with workflows, which have very different structures and execution models from capsul's, so I don't know how you would plug that into our pipelines.
I guess we could also write a copy node in capsul pipelining environment to do so. Actually there is a FileCopyProcess which copies _input files_ in a common working directory, and from which NipypeProcess inherits. We could maybe do something similar for outputs (which is another alternative).

**Comment by denisri** [comment]
`nipype` processes now write their outputs in `derived_data`. Mia processed don't (yet). However there are still questions. I don't think nipype/SPM interfaces allow to write data and run scripts (`.m`) in different directories (am I wrong ?), so right now the scripts are also written in `derived_data`, thus will likely overwrite each another.
Speaking of this, I may be wrong also but using the same directory (`derived_data`) for all processes/.m scripts might cause big trouble when using parallel processing.
So if we want to correctly solve this issue, we may have to change at lower level, in Capsul, the way we use / wrap nipype processes, and also the way MIA processes work. Nipype processes in Capsul are using a wrapping based on Capsul `FileCopyProcess` which allows to copy or symlink files in order to work in a separate or temporary directory - a single one for the whole process. We may need to change it to use several directories for several outputs.
What are the needs and use cases for that ?

**Comment by servoz** [comment]
> nipype processes now write their outputs in derived_data. Mia processed don't (yet).

Yes, that's what I noticed ... and that's why I naively told myself that the change for mia_processes would be easy to achieve. It's also a way to read the new codes because things have changed a lot and I need to understand finely how it works now!
But it's not that simple... and I was just thinking that we should also manage things at a higher level, rather than in mia_processes as it is the case since now... In short, I was getting to your point ...
> However there are still questions. I don't think nipype/SPM interfaces allow to write data and run scripts (.m) in different directories (am I wrong ?),

I'm not a nipype specialist, but the tests I've done since this morning (and before ! - this was one of the reasons (there were several!) why we decided to create our own bricks in mia_processes -) seem to indicate that (that's why I thought it should be handled at a higher level, in capsul ?, as I think we do for pure nipype processes - but I haven't read all that part of the code in detail yet, I've just looked at what happens for a pure nipype process -).
> so right now the scripts are also written in derived_data, thus will likely overwrite each another.
Speaking of this, I may be wrong also but using the same directory (derived_data) for all processes/.m scripts might cause big trouble when using parallel processing.

sure !
I think it would be best to save the .m scripts in a dedicated place (that's why they were saved in project/scrpits before).
Moreover currently for a pure nipype process, at the time of the run a temporary directory is created.
![Screenshot from 2020-11-25 11-47-57](https://user-images.githubusercontent.com/37933899/100217911-4cd7e200-2f14-11eb-9e36-9a447b4056d7.png)
in which there is a symbolic link to the T1 data and the Bold data (which is curious because in_files is just the T1 data) and with the associated json (which may be useless), as well as the .m script and the output file filling up
![Screenshot from 2020-11-25 11-48-07](https://user-images.githubusercontent.com/37933899/100218300-dbe4fa00-2f14-11eb-9d18-b1fe444cda8d.png)
finally when the run is finished, the temporary directory is deleted and the output file is moved up one stage to be saved in derived_data. Except for the previous minor remarks (bold data, json) it's elegant and what we wish, but finally we don't keep the .m script after all ...
![Screenshot from 2020-11-25 11-48-30](https://user-images.githubusercontent.com/37933899/100218607-4007be00-2f15-11eb-98dc-94503c102edb.png)
>So if we want to correctly solve this issue, we may have to change at lower level, in Capsul, the way we use / wrap nipype processes, and also the way MIA processes work. Nipype processes in Capsul are using a wrapping based on Capsul FileCopyProcess which allows to copy or symlink files in order to work in a separate or temporary directory - a single one for the whole process. We may need to change it to use several directories for several outputs.
What are the needs and use cases for that ?

At my level, but of course it doesn't cover all needs, there should be a place dedicated to saving scripts, without them overwriting each other - in project/scripts? there will be a directory for each process? The temporary folder, could be created in /tmp instead of project/data/derived_data, because it is only temporary. And of course the output data in project/data/derived_data.

**Comment by denisri** [comment]
Oh yes, the temporary work directory feature is activated in capsul nipype wrapping, thus all is done in a temp dir, which is fine since it avoids any filename overlap (script files especially). But yes, the side effect then is to completely lose the script files since they are not "official" outputs (they are not part of the process or interface parameters) and so nobody cares about moving them somewhere else. The only solution I see is to modify `NipypeProcess` in Capsul to take care of them, maybe using an additional parameter (script_file(s) or scripts directory).
A few precisions:
* the temp dir is a subdir of the output dir for performance reasons: the output files may be large, and moving them out of the temp dir to the "final" output directory will be very fast since it is always the same filesystem as the final output. If we use /tmp or another temp directory, it may be (and will probably) be a separate filesystem, and moving files to the final output dir will require a full copy, which needs additional time and IO / network bandwidth.
* I don't know why the Bold data (in your example) is also symlinked in the temp dir (I observe the same), it doesn't seem normal to me, I have to investigate...
* if we keep script files somewhere in `project/scripts/` we will have to create unique names for them because they will all end up in the same directory and they will overlap if we do nothing more. How will we name them and keep track of their association with a process run ? (there is no track of them in processes parameters). As a subsidiary question, do we really need to keep them, what are they useful for ? Who will use them ? (maybe for debugging ?)

**Comment by servoz** [comment]
- Ok, I fully understand that for performance reasons, temporary directories should not be put in /tmp. I hadn't thought of that!


> do we really need to keep them, what are they useful for ? Who will use them ? (maybe for debugging ?)

- to be really honest, concerning the scripts.m: No.
Sometimes I was happy to find them, but that was only in the case of debugging.
I doubt that a normal user will want to have access to them...
Ok, let's say that if it's possible to do it easily, even in a dirty way because at the end it will be only for us! [like a project/scripts directory with ProcessName_OrderOfInitialisationInPipeline.m or ProcessName_date.m - with date something like datetime.now().strftime("%Y-%m-%d_%Hh%Mmin%Ss%f") -] so that we can find our way if there are several times the same process in a pipeline) we do it, otherwise we drop it?

**Comment by servoz** [comment]
This issue will be fixed in release 2.x
