### ISSUE TITLE
[Completion bug] Completion only works once

### ISSUE THREAD

**Issue by LStruber** [populse/populse_mia#271]
Minimum steps to reproduce:
- Open your favorite project
- Add a smooth brick in the pipeline manager
- Export all unconnected mandatory plugs
- Select a file in the input node
- Run the brick
- Go to data browser, and see it worked
- Go back to pipeline manager
- Open a new tab
- Add a smooth brick in this tab (or another one)
- Export all unconnected mandatory plugs
- Select a file in the input node
- Run the brick

It fails during initialization with the following message:
![image](https://user-images.githubusercontent.com/86590799/165493381-6ed2c042-66ca-4954-9d97-19ff870e5f13.png)

Tested on a fresh bv_maker, with populse_mia on master and mia_processes on master, both up-to-date

NOTE: If you run the brick alone (without exporting plugs), it works !

By investigating a bit, I identified the problem:
In `init_pipeline()` function of `pipeline_manage_tab.py`, the workflow returned by `workflow_from_pipeline` function (of Capsul) should contains the output file (in example case `smoothed_files`). This is the case at the initialization of the first brick, and not the second time (see `self.workflow.jobs[1].param_dict['smoothed_files']` after creating the workflow in both cases).
This make me think that the issue could come from Capsul... @denisri would you have an idea why "sometimes" the output file is not present in the workflow `param_dict` ?

**Comment by LStruber** [comment]
Note that you can relaunch the first pipeline, even after the error occured

**Comment by denisri** [comment]
I'm looking at it. Completion seems to fail for the second pipeline. I don't know why it's different and why it fails (yet), but I can reproduce the problem.

**Comment by denisri** [comment]
OK I think it's fixed: it did not actually depend on the 1st/second tab in the pipeline manager, but whether you had clicked on the node using the left button before exporting its parameters ;)
I explain:
* when you click on a node, it displays its controller GUI, and while doing it it tries to instantiate a completion engine for its process (using the `Process` instance). Once instantiated, the completion engine is cached and will be reused later.
* When you export the parameters, then complete parameters for the pipeline, the completion system will try to instantiate a completion engine for its nodes, using the `Node` instance, not the `Process` instance (the `Node` here contains a `Process` but is not one). If the completion engine has been cached it will be reused (with the `Process` registered with it), otherwise it will be created (but with the `Node` registered with it). It should work using either the `Node` or the `Process`.
* But in Mia the overload of the completion system had a bug using `Nodes`, it actually expected a `Process`, thus was failing when instantiated using the `Node`. This explains the problem.
It has been fixed now. You can check.

**Comment by servoz** [comment]
@LStruber can you check and report from your side, please ?

**Comment by LStruber** [comment]
It's indeed working now. I close the ticket.
