### ISSUE TITLE
[Installation] Installation failed - TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by BastienCagna** [populse/populse_mia#278]
**Describe the bug**
The installation crash with a core dumped during the third step ("Writing [...]").

**Generated error**
```
$ python install_mia.py 

<class 'FileNotFoundError'>: [Errno 2] Aucun fichier ou dossier de ce type: 'matlab'

Gtk-Message: 15:38:43.098: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/home/bastien/soft/populse_mia_install-master/mia_install_widget.py", line 763, in install
    config_dic = self.load_config(config_file)
  File "/home/bastien/soft/populse_mia_install-master/mia_install_widget.py", line 877, in load_config
    return yaml.load(stream)
TypeError: load() missing 1 required positional argument: 'Loader'
Abandon (core dumped)

```

**To Reproduce**
1. Download and uncompress the archive
2. Check the requirements (python, java, git)
3. Create a new folder for mia processes
4. run python install_mia.py

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Populse_MIA version: the one on the website right now

**Additional context**

**Comment by servoz** [comment]
I feel that you are using an old module,  install_mia.py, (and a way that is no longer supported) to install mia !!!
Please tell me where you got the information to install this way so that I can correct it (due to lack of time the documentation is no longer up to date, it should be updated, sorry).
You want to use mia in casa_distro ?

**Comment by servoz** [comment]
oh I see, [you certainly followed this link ](https://populse.github.io/populse_mia/html/installation/user_installation.htm)(sorry it's one of the first links proposed in the documentation ... I absolutely have to change this documentation ASAP !!!!).
I assume you work at casa_distro.
In this case you just have to create a directory to install things. In this directory you just have to  clone mia_processes, mri_conv and populse_mia.
For example if it's the /home/toto/mia directory:

cd /home/toto/mia
git clone https://github.com/populse/populse_mia.git
git clone  https://github.com/populse/mri_conv.git
git clone  https://github.com/populse/mia_processes.git

To launch mia:
python3 /home/toto/mia/populse_mia/python/populse_mia/main.py

Depending on your conf it is not impossible that you need to install some python libraries ... 
It can be quite boring. If when you start mia you get messages that it can't find a library I recommend this little trick:
cd /home/toto/mia/populse_mia
python3 setup.py install --user
cd /home/toto/mia/mia_processes
python3 setup.py install --user
pip3 uninstall populse_mia mia_processes

After this step there may still be a few libraries to add one by one (launch mia and see what it says), but most will already be installed.
I'm available if you have issues with installation (and I really need to find some time to clean-up and correct the documentation :-))

**Comment by servoz** [comment]
Thank you for opening this ticket!

It has allowed us to fix a lot of things in the installation modules. Indeed these modules were written several years ago and the whole populse project has evolved quite a bit since then.

We took advantage of the rewrite to add an option for installation in casa_distro or on the host. On the host, mia works like in casa_distro, but does not have the DataViewer.

The installer is available from the same link and following the same procedure as described in the documentation (download, unzip, go to the unzipped directory, then do python3 install_mia.py). However, the documentation could also need a little refreshing. We haven't had the time to do it yet, but it's on the todo list!

We have just tested on the host and in casa_distro, it seems to work well now.

I think we can close this ticket now.

Don't hesitate to reopen it if you have any issue with the installation again.
