### ISSUE TITLE
Mia crash after initialisation of the NewSegment brick if we go back to DataBrowser

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#41]
**Describe the bug**
With the NewSegment brick, after initialisation of (or if we run) the pipeline, mia crash if we go from the Pipeline Manager to the Data Browser. The first work around seems to indicate that's happens if the bias image is generated (for exemple by using the channel_info parameter = (0.0001, 60, (False, True)).

**Generated error**
```
Traceback (most recent call last):
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/main_window/main_window.py", line 895, in tab_changed
    self.data_browser.table_data.update_visualized_rows(old_scans)
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/data_browser/data_browser.py", line 1705, in update_visualized_rows
    self.setRowHidden(self.get_scan_row(scan), False)
TypeError: setRowHidden(self, int, bool): argument 1 has unexpected type 'NoneType'

```

**To Reproduce**
1. drag and drop the NewSegment nipype brick in the Editor window
2. use for example (0.0001, 60, (False, True)) as channel_info parameter
3. click the Pipeline>Initialize pipeline button
4. go to Data Browser

**Expected behavior**
No fucking crash !!! never ever !!!!

**Screenshots**
No comment

**Desktop (please complete the following information):**
 - OS: Linux irmage-rico 4.18.18-100.fc27.x86_64
 - Populse_MIA version: 0.0.6

**Additional context**
No comment

**Comment by dhrbn** [comment]
I've just found out that the bug is linked to the database. When we go back to the Data Browser tab, we call the get_documents_names method of the current project's session to update the visualized documents. This method should return the list of the database documents in the order in which the files were added, which is the case except for one case. When a filename contains an uppercase, it is returned as the first element of the list (e.g. BiasField here). So the order of the database documents and the Data Browser are not synchronized and this is what causes the bug. 

To solve this problem, I think we should change the get_documents_names method and make it not case sensitive or return the documents depending on the time that they have been added. What do you think ?

**Comment by servoz** [comment]
Great ! 
For the 2 options you propose, Instinctivement I would say "return the documents depending on the time that they have been added" but I guess "make it not case sensitive" will be easier to do ?
