### ISSUE TITLE
Captions for colors, types etc. in the pipelines 

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#56]
An clear and as complet as possible captions for:
-  color links corresponding to each possible types,
- link thickness for dimension of objects,
- shapes (rectangle, triangle, etc.) for mandatory or optional plugs, etc.

**Comment by servoz** [comment]
I am reopening this issue because it seems that it was closed 2 days ago, as a side effect of the rewrite of the history, which I made in order to delete from the history the large files now followed by git-fs.
The first investigation I conducted seems to indicate that following this operation, some issues have been closed (which I will reopen after some checks). The integrity of the populse_mia project does not seems to have changed (I think the SHA-1 of the commits were changed during the operations, that could explain the side effect observed!)
