### ISSUE TITLE
Alert dialog box to save project not always opened

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#57]
**Expected behavior**
Be sure that an alert dialog box is opened when we close down the main window and that the project has not been saved!

**Actual behavior**
If we close down the main window and that the project has not been saved, the alert dialog box does not always appear

**Comment by M40V** [comment]
The _unsavedModifications_ parameter of project is not always updated after a modification, since [issue 70](https://github.com/populse/populse_mia/issues/70) you can easily see when the project is unsaved thanks to a visual cue next to the title.
If after a modification you notice the title of the project didn't change please signal here the function you used or directly update the _unsavedModifications_ parameter in this function.

`self.unsavedModifications = True` (in data_manager/project.py)
or
`self.project.unsavedModifications = True` (in data_browser.py)

**Comment by servoz** [comment]
I observed some cases where the visual cue next to the title (star) seems to be missing.
- just after importing data from mri_conv (no star next to the title). However, if we close mia, we do have the popup asking if we want to save the project
- if we add a tag in the data browser. However, if we close mia, we do have the popup asking if we want to save the project.
- removing a document (a raw in the Data Browser). However, if we close mia, we do have the popup asking if we want to save the project.
- etc....

I also observed another behavior that may be needs to be improved:
If we import data from mri_conv, we have now data in the Data Browser. 
Then, if we go to the Pipeline Manager we have a popup asking if we want to save the database (usual).
If we click on no and return to the Data Browser we will not see any more data, which is normal since we have not saved the data coming from the mri_conv.
Now if we want to import the same data again from mri_conv we have a popup that asks if we want to overwrite the existing data .... 
This is normal in the current operating way (we have not saved the database, but the data are copied into the raw_data directory at the importing time from mri_conv), but it can be perturbing in some situations or with a user who does not know how mia works. Moreover, is it really desirable? I don't know if it will be necessary to open an issue specially dedicated to this particular point, but it would be necessary to decide if we keep this mode of operation or if we change it.
