### ISSUE TITLE
Continuous Integration is currently failing

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#60]
All the Continuous Integration are currently failing (travis and appveyor) and  this exception is raised:
AttributeError: 'PipelineEditor' object has no attribute 'node_clicked
It seems it happened after https://github.com/populse/capsul/pull/129
the node clicked attribute, was accidentally commented ?

**Comment by denisri** [comment]
I think I understand the cause of the problem: the CI tools install capsul frop pypi, and the recent changes in capsul GUI have not been released to pypi yet, so MIA tests are using a non-matching capsul.
Either we must release a new version of capsul, or MIA tests have to switch (at least temporarily) to the git sources version of capsul.

**Comment by servoz** [comment]
Great! I think it might be cool to release the current version of capsul, soma_worflow and soma_base. I understand that you are working hard for version 3 of capsul, but why not release the current version of these libraries on pypi (for example, capsule release is currently 2.1.2, why not use a version 2.2.1 or 2.1.3, pending the V3 of capsul)? We can discuss this at this afternoon's meeting

**Comment by denisri** [comment]
We have just released on pypi new versions of soma-base, capsul and soma-workflow:
* soma-workflow: both versions 2.10 (Pyro3, python2 only) and 3.0 (zmq, python 2 and 3)
* soma-base: v4.6.4
MIA tests still fail however, there seems to be a bug in nodes size handling in pipeline_developper_view. I'll try to have a look at it.

**Comment by denisri** [comment]
I have fixed the nodes position/size issue in capsul, and released anoter version (2.2.1).
Populse_mia tests still fail, but this is not caused by capsul any longer:

======================================================================
ERROR: test_zz_check_modifications (__main__.TestMIAPipelineManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./python/populse_mia/test.py", line 2265, in test_zz_check_modifications
    pipeline_editor_tabs.get_current_editor().check_modifications()
  File "/home/travis/build/populse/populse_mia/python/populse_mia/pipeline_manager/pipeline_editor.py", line 1234, in check_modifications
    sub_pipeline_filename = find_filename(dic['Paths'], sub_pipeline_list, sub_pipeline_name)
  File "/home/travis/build/populse/populse_mia/python/populse_mia/pipeline_manager/pipeline_editor.py", line 1801, in find_filename
    for f in os.listdir(new_path):
FileNotFoundError: [Errno 2] No such file or directory: '../../processes/User_processes/test_pipeline'

**Comment by servoz** [comment]
Great ! Thanks Denis. As soon as I get some free time, I will see too

**Comment by denisri** [comment]
Well actually yesterday evening after my last commit, tests passed, but I don't know why it behaved differently...

**Comment by servoz** [comment]
Finally close with c53ca848d35441da9f718a0acfa0c0bf48b8d4e9
