### ISSUE TITLE
Pipeline execution in Docker images

### ISSUE THREAD

**Issue by brosscle** [populse/populse_mia#61]
I think that Docker can be a useful tool when dealing with pipeline or brick execution.
Maybe we can add a new optional parameter in each brick that will be the path to a docker image. Then the brick will be executed in this image. The main benefit is that we will be able to execute a brick in an image containing a specific version of a software. Then change the image docker will change the version of this software. 
I believe it will be useful to be able to modulate the environment in which our brick (or the whole pipeline) is executed.

**Comment by denisri** [comment]
Docker or singularity, yes (or maybe any other kind of virtualization or virtual machine), the idea is very interesting. We are thinking about it actually, rather in capsul and/or soma-workflow because these are the tools which will actually run jobs. A few things have been started, but more work is needed on this topic.
What is already working by now is the possibility to have a "container_command" prefix (or wrapper) to the actual job command in soma-workflow jobs. One can be specified globally for a computing resource, and each job may be specialized with its own container config. But the link with capsul processes is still unclear: if a process has a hard-coded container specification, then the process is not "portable" to a different environment any longer, so this process / container link has to be indirect and should probably be done through a config file or an additional software layer.
For instance a process would be "marked" to be compatible (let's say this) with a container identifier, but the way the container is actually run (path, container type, options) should be specified on the computing resource server side (so probably by soma-workflow) because the same process could run on a standard machine, or a cluster, which may use containers differently (or not use containers at all).
This should be further discussed, of course...

**Comment by servoz** [comment]
Starting from BrainVISA 5.0, [the software is distributed using virtualization](https://brainvisa.info/web/download.html). Populse is moving also toward this direction.
