### ISSUE TITLE
sys.exit() in info.py

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#81]
**Expected behavior**
We expect info.py to provide info, not to decide to stop the whole program. I think in a general way, a module (as a library tool) could decide not to import for some reason (raise an ImportError exception typically) but never exit the calling program.

**Actual behavior**
from python2, import populse_mia.info exits the program, with no way to avoid it.

**Additional context**
The python compatibility check could be done from another place: either when starting the application, or in setup.py for packaging.
We need to access the package info even when we cannot actually use populse_mia: we import the info module within our sources/build/packlaging system to make the list of projects, even if they are not used in the current context. So we don't expect info.py to exit the program upon importation, because currently it exits the whole build system.

**Comment by servoz** [comment]
I totally agree that it was inappropriate to put the sys.exit () in the info.py file.

In fact, 2 days ago you made a change accordingly (to correct this inappropriate feature) in the info.py file (raise exception instead of sys.exit ()).

As you know, due to an unfortunate rewrite of the history, we returned to the last commit just before the history rewriting commit, yesterday, and then we added the commits that had been done after this commit. So two commits you had done were lost. We did not want to add them ourselves to give you the opportunity to do it yourself and protect your work as an author ([Rendre à César ce qui est à César !](https://github.com/populse/populse_sandbox/issues/19), your commit 4407981c0c1a6e1f155180722389519c97433444). 

So you can push again your commit changing the sys.exit() use in teh info.py. Or:

We do unit tests only for Python3.5-3.6-3.7. It seems important to remind the user that apart from these versions of Python, nothing is guaranteed. As you proposed, we can also just put a message accordingly at the launch (main.py) rather than in setup.py or info.py. The sys.exit () is maybe a bit excessive ...

**Comment by denisri** [comment]
OK. Actually I opened this ticket because I'd like to do it another way: the info.py should not fail at all (not raise an exception) in order to still provide information about the project even if it cannot run in the current environment, and move the error/message to another place (main.py seems good, and I don't know if you think it's useful in setup.py when packaging).
I'll do that soon...
