### ISSUE TITLE
typo during importing

### ISSUE THREAD

**Issue by blemasso** [populse/populse_mia#83]
**Describe the bug**
there is a typo in the window : "adding the paths"
--> a "P" of "Please" is missing 

![image](https://user-images.githubusercontent.com/17830607/57618502-e682ad00-7583-11e9-8beb-e812486693d0.png)

**Comment by servoz** [comment]
Please, can you give the minimal steps to reproduce (I currently not observe this)

**Comment by blemasso** [comment]
Here are the steps to get this popup:
 - I import new data ("Import")
 - I add Bruker data to the basket
 - I clic on "export to MIA"
 - I clic on "Ok" in the window 'log message'
 - this window appear with the missing "P"

**Comment by M40V** [comment]
I managed to reproduce your steps but I didn't see the typo.
The window "adding the path" is defined in the method _add_rows()_ from the file data_browser.py (line 960), there is no typo in the code.
I think you can't see the first letter due to the size of your window, can you indicate us if you see the "P" if you try to resize the "adding the path" window when it appears ?

**Comment by blemasso** [comment]
Ok, you are right.
The problem come from the size of the window. I try to resize it, but I can not.
I do not know if it is possible, but if you make a window is little be larger it might solve this issue.
Otherwise, it is not a big issue and you can leave it as is :)

**Comment by servoz** [comment]
We will initialise a default size ASAP, when instantiating this window. We keep this ticket open to don't forget it!

**Comment by servoz** [comment]
Normally, the necessary improvement have been done (this ticket is therefore closed).

Please, @blemasso, do not hesitate to report (and open this ticket again) if this issue is not solved on your side or if you see this issue again with other windows!
