### ISSUE TITLE
Enabling developer mode needs five clicks

### ISSUE THREAD

**Issue by BlancaNietoPetinal** [populse/populse_mia#91]
**Describe the bug**
Changing from the default "Clinical Mode" to "Developer Mode" in the MIA preferences requires five clicks on the check box, not only one.
Once the developer mode is active, the check box disappears. Upon closing and re-opening the dialogue, the check box reappears.

**Generated error**
None

**To Reproduce**
1. In a fresh install, open the MIA preferences. Clinical mode is active.
2. Click on the check box. Nothing happens
3. Click four more times. The check box disappears.
4. Close and re-open the dialogue. The empty check box is showing correctly

**Expected behavior**
A single click should be sufficient. Unless this is a feature to prevent accidental deactivation of clinical mode?

**Screenshots**
![Screenshot from 2019-06-11 17-10-03](https://user-images.githubusercontent.com/26384451/59284163-12b94880-8c6c-11e9-9baf-3b9dcb95d9af.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Populse_MIA version latest git

**Comment by servoz** [comment]
Sorry Madam, this is not a bug..... just a feature..... Hum hum :-)
 We had thought about this in order not to make the developer mode available too easily (without using a password, etc...).
A priori, our idea is too simplistic since you have found a way to switch from clinical mode to developer mode very quickly! :-)
I close the ticket but we will have to change the way to switch from clinical to developer mode ...
