### ISSUE TITLE
 Automatic adding values for the existing tags when new objects are processed

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#92]
As far as I can remember, a special effort has been made in the past to automatically add tags values for new objects (images, etc.) created during a process (brick, pipeline, etc.).

This must be done at two levels. For the document (the line in the data browser) and for the special "Bricks" tag.

- For the document, all tag values are currently set to "Not defined" for a new object created. Normally, all tags must inherit from objects that enters the brick.

- For the sub-browser under the special "Bricks" tag all the tags corresponding to the parameters of the brick are added, except the two tags "Exec" and "Exec Time".

Unless I'm mistaken, these features existed in the past.

**Comment by servoz** [comment]
EDIT:
In fact, the latest tests performed indicate that the job is done, only for "mia bricks" (created in mia, i. e. in User_processes or mia_processes libraries).
Could be very desirable to extend this feature to the nipype library!
Leaving this ticket open to don't forget to do it ASAP.

**Comment by M40V** [comment]
Currently the tags are added automatically for mia bricks and not for nipype one because this feature requires an inheritance dictionary, which is only defined with mia bricks.

This inheritance dictionary is necessary to determine the parent file (scan/document) from which to inherit the tags. We could try to determine it automatically for nipype processes when there is only one scan involved in the process.
If there are multiple files involved, we could show a pop-up with multiple choices for the user to select the parent file.

**Comment by servoz** [comment]
As far as I can remember our discussion:
- correct the problem when more than one pipeline is being initialized.
- Clarify messages in the popup window
- Did I forget something?
